const RoundWinCountsTypes = {
  INCREASE_WIN_COUNT: "INCREASE_WIN_COUNT",
  INCREASE_ROUND_COUNT: "INCREASE_ROUND_COUNT",
  RESET_HEADER_COUNTERS: "RESET_HEADER_COUNTERS"
};

export default RoundWinCountsTypes;
