const enum ROUND_WIN_COUNTERS_TYPES {
  INCREASE_WIN_COUNT = "INCREASE_WIN_COUNT",
  INCREASE_ROUND_COUNT = "INCREASE_ROUND_COUNT",
  RESET_HEADER_COUNTERS = "RESET_HEADER_COUNTERS",
}

export default ROUND_WIN_COUNTERS_TYPES;
